### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by Jadus420** [winneon/neutron#1]
I've installed Neutron.Setup.0.2.5.exe but I'm finding it doesn't start. I can see it briefly appear in task manager and then it goes.

My Elite game files are installed in the default location and i'm running Windows 10 x64. Do I need anything else installed for this to run?

**Comment by win0na** [comment]
I'll look into this in the morning, I'm currently trying to sleep after a rough day. Thanks for letting me know about this.

**Comment by Jadus420** [comment]
Just FYI. I installed v0.2.3 tonight, i got some java script errors on install but it has worked flawlessly all night. I've covered about 6k Ly on my way to Colonia and it's been brilliant. Thanks so much.

**Comment by win0na** [comment]
You're welcome! I found the problem and am currently working to fix it.

**Comment by win0na** [comment]
Fixed in 643e4f638c1a52cbc5607fba1b7c2e428d41b4ae. Update to v0.2.7.
