### ISSUE TITLE
Neutron only reads "Status.json" file in journal directory

### ISSUE THREAD

**Issue by coolh** [winneon/neutron#4]
Thanks for your great app, I love the clean interface.
I found the following issue:

After app start it shows "location unknown" (I tried to restart the app, and jump to another system)
I used a process monitor to see what happened and I discovered that its only reading the Status.json file. 
If I delete that file, then the journal is read and the location is updated. 
As soon as the Status.json file its created the app jump to that file again and stop updating location.

Seems to me that its taking into account the last file in the directory ordered by name, I tried to create a file starting with Z and the app jumped to it.

See attached screenshoot

Thanks a lot for your help
Best regards

Fernando-

PD: Excuse my english, its not my native language

![filemon](https://user-images.githubusercontent.com/18689369/42179645-1f5c2dde-7e0b-11e8-9ea6-f68ab0a3a769.jpg)

**Comment by coolh** [comment]
After further investigation I managed to isolate the problem on journal.js file:
`input: fs.createReadStream(path.join(this.directory, files[files.length - 1]))`

In my system the content of "files" array is:

[ 'Journal.180702143309.01.log',
  'Journal.180702145030.01.log',
  'Status.json' ]

So you are getting only the last one which is Status.json.

I will work in a patch to the issue filtering only .journal files in the array

**Comment by coolh** [comment]
I solved it adding the following filter before fs.createReadStream() function:
      `files = files.filter(function (str) { return str.indexOf('Journal') !== -1; });`
I tested it and it works for me.

**Comment by win0na** [comment]
`Status.json` must be a new file that was added in an update to ED. I'll verify the added code doesn't break anything and then add it. Thanks for looking into this!

**Comment by win0na** [comment]
Fixed with https://github.com/winneon/neutron/commit/7173e0ba1aed3e2d5938e6c3986755db1a89a3f8.
